checksumBehavior: update

compressionLevel: 2

cacheFolder: './.yarn/cache'

cloneConcurrency: 1

enableGlobalCache: true

npmAlwaysAuth: true

nodeLinker: node-modules

npmAuthIdent: '${ARTIFACTORY_USERNAME}:${ARTIFACTORY_PASSWORD}'

npmRegistryServer: 'https://jfrog.skillz.com/artifactory/api/npm/npm/'

yarnPath: .yarn/releases/yarn-4.1.1.cjs
